title: Allen Yang
theme: just-the-docs

aux_links:
  Google Scholar: https://scholar.google.com/citations?hl=en&user=d8JqqC8AAAAJ
  Github: https://github.com/Allenyang2
  Linkedin: https://www.linkedin.com/in/allen-yang347/
  


search_enabled: false
color_scheme: dark 
