title: Allen Yang
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Github: https://github.com/Allenyang2
  Google Scholar: https://scholar.google.com/citations?hl=en&user=d8JqqC8AAAAJ
  


search_enabled: false
color_scheme: dark 

image: "/assets/1619208044553.jpg" 
